[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mobcalibrate"
version = "0.1.0"
description = "Calibration tools for mobile phone location data"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
